---
### [Change System Name] ishizawa-aws-test
### [Change Domain Name] ishizawa-aws-test.site
## CloudFront certificate needs to be created in the us-east-1 region.
## ELB certificate needs to be created in the ap-northeast-1 region.
AWSTemplateFormatVersion: '2010-09-09'
Description: Create Certificate

Parameters:
  SystemName:
    Description: System name
    Type: String
    Default: ishizawa-aws-test
  DomainName:
    Description: Domain Name
    Type: String
    Default: ishizawa-aws-test.site
  Environment:
    Description: Environment
    Type: String
    Default: prod
    AllowedValues:
      - prod
      - stg
      - dev

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Environment Configuration"
        Parameters:
          - SystemName
          - DomainName
          - Environment

Conditions:
  isProd: !Equals [ !Ref Environment, prod ]

Resources:
  ## Certificate
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !If [ isProd, !Ref DomainName, !Sub "${Environment}.${DomainName}" ]
      SubjectAlternativeNames:
        - !If [ isProd, !Sub "*.${DomainName}", !Sub "*.${Environment}.${DomainName}" ]
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${Environment}-certificate-${AWS::Region}
      ValidationMethod: DNS

Outputs:
  Certificate:
    Value: !Ref Certificate
    Export:
      Name: !Sub ${AWS::StackName}-Certificate

  ## 以下二つのリソースは現段階では利用しないもの。将来的に利用するかも
  CertificateDomainName:
    Value: !If [ isProd, !Ref DomainName, !Sub "${Environment}.${DomainName}" ]
    Export:
      Name: !Sub ${AWS::StackName}-CertificateDomainName

  ## SAN
  CertificateSubjectAlternativeName1:
    Value: !If [ isProd, !Sub "*.${DomainName}", !Sub "*.${Environment}.${DomainName}" ]
    Export:
      Name: !Sub ${AWS::StackName}-CertificateSubjectAlternativeName1
