---
### [Change Name] IshizawaYusaku
AWSTemplateFormatVersion: "2010-09-09"
Description: Create AWS IAM User etc.

Resources:
  ## IAM: Group
  GroupAdministrators:
    Type: AWS::IAM::Group
    Properties:
      GroupName: Administrators
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  ## IAM: User
  IshizawaYusaku: ### [Change Name]
    Type: AWS::IAM::User
    Properties:
      UserName: ishizawa.yusaku ### [Change Name]
      LoginProfile:
        Password: ishizawa@730
        PasswordResetRequired: true
      Groups:
        - !Ref GroupAdministrators

Outputs:
  ## IAM: Group
  GroupAdministrators:
    Value: !GetAtt GroupAdministrators.Arn
    Export:
      Name: !Sub ${AWS::StackName}-GroupAdministrators

  ## IAM: User
  IshizawaYusaku: ### [Change Name]
    Value: !GetAtt IshizawaYusaku.Arn
    Export:
      Name: !Sub ${AWS::StackName}-IshizawaYusaku ### [Change Name]