version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./containers/app/Dockerfile
    environment:
      MYSQL_HOST: ishizawa-aws-test-prod-rds.cluster-ccnp8owbry6z.ap-northeast-1.rds.amazonaws.com
      MYSQL_DATABASE: ishizawa-aws-test-prod-rds
      MYSQL_USER: root
      MYSQL_PASSWORD: 5ma6QbV9CbFsG8Esg9nYFRAitRd9bdGw
      RAILS_ENV: development
      RAILS_CONFIG_HOSTS: .ishizawa-aws-test.site
    volumes:
      - ./app/:/awsmaster/
    ports:
      - "3000:3000"
    container_name: app
    restart: always
  web:
    build:
      context: .
      dockerfile: ./containers/web/Dockerfile
    ## envsubstコマンドで設定ファイルに環境変数を埋め込む
    ## exec nginx -g 'daemon off;'はnginxをdaemon化(background実行)する事を防ぐ為のコマンド
    command: /bin/bash -c "envsubst '\$\$NGINX_BACKEND' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    environment:
      NGINX_BACKEND: app
    volumes:
      - ./containers/web/nginx.conf:/etc/nginx/nginx.conf
      - ./containers/web/default.conf.template:/etc/nginx/conf.d/default.conf.template
    ports:
      - "80:80"
    depends_on:
      - app
    container_name: web
    restart: always