AWSTemplateFormatVersion: "2010-09-09"
Description: Create EC2 Launch Template and EC2 Auto Scaling Group.

Mappings:
  EnvironmentMap:
    prod:
      AutoScalingDesiredCapacity: 2
      AutoScalingMinSize: 1
      AutoScalingMaxSize: 3
    stg:
      AutoScalingDesiredCapacity: 2
      AutoScalingMinSize: 1
      AutoScalingMaxSize: 3
    dev:
      AutoScalingDesiredCapacity: 1
      AutoScalingMinSize: 1
      AutoScalingMaxSize: 3

Parameters:
  SystemName:
    Description: System Name
    Type: String
    Default: ishizawa-aws-test
  Environment:
    Description: Environment
    Type: String
    Default: prod
    AllowedValues:
      - prod
      - stg
      - dev
  ResourceName:
    Description: Resource Name
    Type: String
    Default: viaelb
  EC2ImageId:
    Description: >
      Specifies the AMI ID for your container instances.
      https://ap-northeast-1.console.aws.amazon.com/ec2/v2/
    Type: AWS::EC2::Image::Id
    Default: ami-0466ea3cdd455339d
  UseSubnetProtected:
    Description: Use Protected Subnet
    Type: String
    Default: true
    AllowedValues:
      - true
      - false

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Environment Configuration"
        Parameters:
          - SystemName
          - Environment
          - ResourceName
          - EC2ImageId
          - UseSubnetProtected

Conditions:
  isProd: !Equals [ !Ref Environment, prod ]
  isNotProd: !Not [ !Equals [ !Ref Environment, prod ] ]
  ShouldUseSubnetProtected: !Equals [ !Ref UseSubnetProtected, true ]

Resources:
  ## EC2: LaunchTemplate
  EC2LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub ${SystemName}-${Environment}-${ResourceName}-ec2autoscaling
      LaunchTemplateData:
        ImageId: !Ref EC2ImageId
        IamInstanceProfile:
          Name:
            Fn::ImportValue: !Sub ${SystemName}-${Environment}-${ResourceName}-ec2-IAMInstanceProfile
        InstanceInitiatedShutdownBehavior: terminate
        Monitoring:
          Enabled: false
        # EbsOptimized: true ## EbsOptimized is not available for t2 instance type.
        NetworkInterfaces:
          - DeviceIndex: 0
            Description: Primary network interface
            AssociatePublicIpAddress: !If [ ShouldUseSubnetProtected, false, true ]
            Groups:
              - Fn::ImportValue: !Sub ${SystemName}-${Environment}-${ResourceName}-ec2-EC2SecurityGroup
        ## To change the volume type from gp2 to gp3
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              VolumeSize: 8
              VolumeType: gp3
              # Encrypted: true
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: !Sub ${SystemName}-${Environment}-${ResourceName}-ec2autoscaling
          - ResourceType: volume
            Tags:
              - Key: Name
                Value: !Sub ${SystemName}-${Environment}-${ResourceName}-ec2autoscaling
        # UserData:
        #   Fn::Base64: !Sub |
        #     #!/bin/bash

  ## AutoScaling: AutoScalingGroup
  EC2AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    ## If you do not want AWS CloudFormation to change any of the group size property values
    ## when you have a scheduled action in effect, use the AutoScalingScheduledAction update policy
    ## and set IgnoreUnmodifiedGroupSizeProperties to true to prevent AWS CloudFormation
    ## from changing the MinSize, MaxSize, or DesiredCapacity properties
    ## unless you have modified these values in your template.
    ## Ref. https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-attribute-updatepolicy.html
    ## >> IgnoreUnmodifiedGroupSizeProperties
    UpdatePolicy:
      AutoScalingScheduledAction:
        IgnoreUnmodifiedGroupSizeProperties: true
    Properties:
      AutoScalingGroupName: !Sub ${SystemName}-${Environment}-${ResourceName}-ec2autoscaling
      MixedInstancesPolicy:
        InstancesDistribution:
          OnDemandBaseCapacity: 0
          OnDemandPercentageAboveBaseCapacity: 0
          SpotAllocationStrategy: capacity-optimized
          # SpotInstancePools: 4 ## Valid only when the Spot allocation strategy is lowest-price.
        LaunchTemplate:
          LaunchTemplateSpecification:
            LaunchTemplateId: !Ref EC2LaunchTemplate
            Version: !GetAtt EC2LaunchTemplate.LatestVersionNumber
          Overrides:
            ## Since the Memory is the same below, WeightedCapacity is not specified.
            - InstanceType: t2.micro
            - InstanceType: t3a.micro
      VPCZoneIdentifier:
        Fn::If:
          - ShouldUseSubnetProtected
          - - Fn::ImportValue: !Sub ${SystemName}-${Environment}-vpc-SubnetProtectedA
            - Fn::ImportValue: !Sub ${SystemName}-${Environment}-vpc-SubnetProtectedC
            - Fn::ImportValue: !Sub ${SystemName}-${Environment}-vpc-SubnetProtectedD
          - - Fn::ImportValue: !Sub ${SystemName}-${Environment}-vpc-SubnetPublicA
            - Fn::ImportValue: !Sub ${SystemName}-${Environment}-vpc-SubnetPublicC
            - Fn::ImportValue: !Sub ${SystemName}-${Environment}-vpc-SubnetPublicD
      TargetGroupARNs:
        - Fn::ImportValue: !Sub ${SystemName}-${Environment}-${ResourceName}-ec2-ELBTargetGroup
      HealthCheckGracePeriod: 300
      DesiredCapacity: !FindInMap [ EnvironmentMap, !Ref Environment, AutoScalingDesiredCapacity ]
      MinSize: !FindInMap [ EnvironmentMap, !Ref Environment, AutoScalingMinSize ]
      MaxSize: !FindInMap [ EnvironmentMap, !Ref Environment, AutoScalingMaxSize ]

  ## AutoScaling: ScheduledAction
  ScheduledActionScaleOut:
    Condition: isProd
    Type: AWS::AutoScaling::ScheduledAction
    Properties:
      AutoScalingGroupName: !Ref EC2AutoScalingGroup
      DesiredCapacity: !FindInMap [ EnvironmentMap, !Ref Environment, AutoScalingDesiredCapacity ]
      MinSize: !FindInMap [ EnvironmentMap, !Ref Environment, AutoScalingMinSize ]
      MaxSize: !FindInMap [ EnvironmentMap, !Ref Environment, AutoScalingMaxSize ]
      Recurrence: "0 22 * * SUN-THU" ## [Cron] Monday-Friday 07:00(JST) @ Prod

  ScheduledActionScaleIn:
    Condition: isProd
    Type: AWS::AutoScaling::ScheduledAction
    Properties:
      AutoScalingGroupName: !Ref EC2AutoScalingGroup
      DesiredCapacity: !FindInMap [ EnvironmentMap, !Ref Environment, AutoScalingMinSize ]
      MinSize: !FindInMap [ EnvironmentMap, !Ref Environment, AutoScalingMinSize ]
      MaxSize: !FindInMap [ EnvironmentMap, !Ref Environment, AutoScalingMaxSize ]
      Recurrence: "0 14 * * MON-FRI" ## [Cron] Monday-Friday 23:00(JST) @ Prod

  ScheduledActionStart:
    Condition: isNotProd
    Type: AWS::AutoScaling::ScheduledAction
    Properties:
      AutoScalingGroupName: !Ref EC2AutoScalingGroup
      DesiredCapacity: !FindInMap [ EnvironmentMap, !Ref Environment, AutoScalingDesiredCapacity ]
      MinSize: !FindInMap [ EnvironmentMap, !Ref Environment, AutoScalingMinSize ]
      MaxSize: !FindInMap [ EnvironmentMap, !Ref Environment, AutoScalingMaxSize ]
      Recurrence: "50 22 * * SUN-THU" ## [Cron] Monday-Friday 07:50(JST) @ Not Prod

  ScheduledActionStop:
    Condition: isNotProd
    Type: AWS::AutoScaling::ScheduledAction
    Properties:
      AutoScalingGroupName: !Ref EC2AutoScalingGroup
      DesiredCapacity: 0
      MinSize: 0
      MaxSize: !FindInMap [ EnvironmentMap, !Ref Environment, AutoScalingMaxSize ]
      Recurrence: "0 13 * * MON-FRI" ## [Cron] Monday-Friday 22:00(JST) @ Not Prod

Outputs:
  ## EC2: LaunchTemplate
  EC2LaunchTemplate:
    Value: !Ref EC2LaunchTemplate
    Export:
      Name: !Sub ${AWS::StackName}-EC2LaunchTemplate

  EC2LaunchTemplateDefaultVersionNumber:
    Value: !GetAtt EC2LaunchTemplate.DefaultVersionNumber
    Export:
      Name: !Sub ${AWS::StackName}-EC2LaunchTemplateDefaultVersionNumber

  EC2LaunchTemplateLatestVersionNumber:
    Value: !GetAtt EC2LaunchTemplate.LatestVersionNumber
    Export:
      Name: !Sub ${AWS::StackName}-EC2LaunchTemplateLatestVersionNumber

  ## AutoScaling: AutoScalingGroup
  EC2AutoScalingGroup:
    Value: !Ref EC2AutoScalingGroup
    Export:
      Name: !Sub ${AWS::StackName}-EC2AutoScalingGroup

  ## AutoScaling: ScheduledAction
  ScheduledActionScaleOut:
    Condition: isProd
    Value: !Ref ScheduledActionScaleOut
    Export:
      Name: !Sub ${AWS::StackName}-ScheduledActionScaleOut

  ScheduledActionScaleIn:
    Condition: isProd
    Value: !Ref ScheduledActionScaleIn
    Export:
      Name: !Sub ${AWS::StackName}-ScheduledActionScaleIn

  ScheduledActionStart:
    Condition: isNotProd
    Value: !Ref ScheduledActionStart
    Export:
      Name: !Sub ${AWS::StackName}-ScheduledActionStart

  ScheduledActionStop:
    Condition: isNotProd
    Value: !Ref ScheduledActionStop
    Export:
      Name: !Sub ${AWS::StackName}-ScheduledActionStop
